### ISSUE TITLE
Line 97 Apache%20Hive/Installation%20guide <value>App</value>

### ISSUE THREAD

**Issue by kwanchaiEurviriyanukul** [Thirapat/BigData#2]
https://github.com/Thirapat/BigData/blob/master/Apache%20Hive/Installation%20guide

<value>App</value>
Do we need to change to <value>APP</value> to conform username we created at line 
22 CREATE USER 'APP'@'localhost' IDENTIFIED BY 'mine';

thank you

**Comment by Thirapat** [comment]
thank you
